name: road_traffic_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core dependencies
  - python=3.9
  - pip
  - pre-commit
  - pytest
  - pytest-cov

  # Data handling
  - pandas
  - numpy
  - dask-ml

  # Visualisation
  - matplotlib
  - seaborn

  # Machine learning
  - lightgbm
  - scikit-learn
  - glum

  # Interactive environments
  - ipykernel
  - jupyterlab

  # YAML handling
  - pyyaml
